app:
  path: /path/to/the/app/dir
  static_path: /path/to/the/app/dir/static
  static_route: /static/
  gzip: true
mongo:
  servers: localhost
  name: wildling
  port: 27017
memcached:
  servers: localhost:11211
http:
  port: 8000
json:
  port: 8001